version: '3.8'
services:
  sentinel-db:
    image: alpine
    container_name: sentinel-db
    command: sh -c "while true; do sleep 1; done"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"